@startuml
left to right direction
skinparam shadowing false
hide methods
hide fields

package "click" <<Frame>> {
}

package hexrec
{
    package utils {
    }

    package xxd {
    }

    package blocks
    {
        class block <<tuple>> {
            + address: int
            + data: bytes
        }
        show block fields

        class SparseItems <<bytearray>> {
            + blocks: block[]
        }
        show SparseItems fields

        SparseItems o-- "*" block
    }

    package records
    {
        abstract class Record
        {
            + address: int
            + tag: enum
            + data: bytes
            + count: int
            + checksum: int
        }
        show Record fields

        class BinaryRecord
        class IntelRecord
        class MotorolaRecord
        class TektronixRecord

        Record <|-left- BinaryRecord
        Record <|-down- IntelRecord
        Record <|-down- MotorolaRecord
        Record <|-down- TektronixRecord

        enum MotorolaTag
        enum IntelTag
        enum TektronixTag

        MotorolaRecord  .down.> MotorolaTag
        IntelRecord     .down.> IntelTag
        TektronixRecord .down.> TektronixTag
    }

    package cli {
    }

    records ..> blocks
    cli ..> SparseItems
    cli ..> records
    cli ..> click
    cli ..> xxd
}

@enduml
